CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  password VARCHAR(100) NOT NULL,
  bio VARCHAR(1000),
  display_name VARCHAR(50),
  stream_name VARCHAR(50),
  stream_key VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS follows (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  follower_id INT,
  follows_id INT,
  FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (follows_id) REFERENCES users(id) ON DELETE CASCADE
);
