name: blaze

services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - MEDIAMTX_API_URL=http://mediamtx:9997
  
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  
  mediamtx:
    image: bluenviron/mediamtx
    restart: always
    ports:
      - 1935:1935
      - 8888:8888
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
