name: blaze

services:
  api:
    build: .
    restart: always
    depends_on:
      - postgres
      - mediamtx
    ports:
      - 8080:8080
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  mediamtx:
    image: bluenviron/mediamtx
    restart: always
    ports:
      - 1935:1935
      - 8888:8888
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
